### ISSUE TITLE
Convert BannedKeywordsBag to use a Set internally

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [general-language-syntax/GLS#325]
> _New to GLS for [#hacktoberfest](https://hacktoberfest.digitalocean.com/)? Welcome!_
> _Be sure to read the docs at [glslang.org](https://www.glslang.org) and play on [aka.ms/gls-demo](https://aka.ms/gls-demo) to familiarize yourself._

It looks better and is probably more efficient.

**Comment by gerardogalvez** [comment]
I'd like to work on this!
