### ISSUE TITLE
Replace any command name string literals with CommandName references

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [general-language-syntax/GLS#326]
> _New to GLS for [#hacktoberfest](https://hacktoberfest.digitalocean.com/)? Welcome!_
> _Be sure to read the docs at [glslang.org](https://www.glslang.org) and play on [aka.ms/gls-demo](https://aka.ms/gls-demo) to familiarize yourself._

`convertCommon("type")` is a common example. It should be `convertCommon(CommandNames.Type)`.

**Comment by jsawo** [comment]
I'd like to do this one

**Comment by JoshuaKGoldberg** [comment]
Great!
