### ISSUE TITLE
Solidify a design doc format

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [general-language-syntax/GLS#34]

**Comment by faulda** [comment]
Should probably include in the doc:
- syntax (if applicable) with examples
- language properties used with examples
- test coverage

**Comment by faulda** [comment]
- whether to use markdown, plain text, or another format

**Comment by faulda** [comment]
We should probably close on this before we add too many more design docs that then need to be updated to fit the format.

**Comment by JoshuaKGoldberg** [comment]
Agreed. Let's say what's currently in PR should go through, then this and #68 solidified.

**Comment by faulda** [comment]
Currently developing in #85
