### ISSUE TITLE
Some or all Python math operations require importing math

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [general-language-syntax/GLS#346]
> _New to GLS for [#hacktoberfest](https://hacktoberfest.digitalocean.com/)? Welcome!_
> _Be sure to read the docs at [glslang.org](https://www.glslang.org) and play on [aka.ms/gls-demo](https://aka.ms/gls-demo) to familiarize yourself._

Consider the following GLS:

```gls
math floor : 3.5
```

What happens now when outputting Python:
```python
floor(3.5)
```

What should happen (as per [repl.it/languages/python3](https://repl.it/languages/python3)):

```python
import math

math.ceil(3.5)
```

The Python language properties in GLS should be looked over and any operations requiring the `math` module need to be fixed.

`math ceil` is an example command that needs it (noticed in #344).

**Comment by larryprice** [comment]
See #348
