### ISSUE TITLE
Get rid of the PythonicLanguage and CLikeLanguage files

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [general-language-syntax/GLS#373]
> _New to GLS for [#hacktoberfest](https://hacktoberfest.digitalocean.com/)? Welcome!_
> _Be sure to read the docs at [glslang.org](https://www.glslang.org) and play on [aka.ms/gls-demo](https://aka.ms/gls-demo) to familiarize yourself._

Using abstract classes for groups of language properties is a nice idea, but makes it a little more confusing to onboard or work with... The files should just be deleted and properties manually added to the subclasses.

**Comment by Oire** [comment]
I take this, also :).

**Comment by JoshuaKGoldberg** [comment]
Great!
