### ISSUE TITLE
"Itteration" should be "iteration"

### ISSUE THREAD

**Issue by Oire** [general-language-syntax/GLS#401]
I would like to claim this issue for my Hacktoberfest challenge :).  
This is seen in several places through the languages definitions: the word "iteration" is mistyped as "itteration".

**Comment by JoshuaKGoldberg** [comment]
Good catch :)

**Comment by zorawar87** [comment]
Hi! What files do you want "Itteration"  changed to "iteration"?

I could resolve the issue with a simple sed statement
