### ISSUE TITLE
Consider using object literals or auto-counter by default in Ruby enums

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [general-language-syntax/GLS#46]
Current:

``` gls
enum start : Direction
    enum member : Unknown 0 ,
    enum member : Horizontal 1 ,
    enum member : Vertical 2
enum end
```

``` ruby
class Direction {
    Unknown = 0
    Horizontal = 1
    Vertical = 2
}
```

Values must be provided because enums aren't built into the language.
But, what if the values defaulted in GLS to `{}`?

``` ruby
class Direction {
    Unknown = 0
    Horizontal = {}
    Vertical = {}
}
```

Pros:
- GLS wouldn't have to provide a value

Cons:
- Integer arithmetic wouldn't be possible anymore
- Muddied semantic meaning

**Comment by faulda** [comment]
Integer arithmetic with the enum values? Or larger scope than that?

Also, would integer arithmetic still work if the user specified an integer value for each name?

**Comment by JoshuaKGoldberg** [comment]
I was hoping for something like http://www.alanzucconi.com/2015/07/26/enum-flags-and-bitwise-operators/ to be possible.

I'ts inconvenient to be required to specify every enum.

**Comment by JoshuaKGoldberg** [comment]
An auto-counter could work something like:

```gls
enum start auto : Direction
    enum member : Unknown ,
    enum member : Horizontal ,
    enum member : Vertical
enum end
```

```ruby
class Direction
    enumCount = 0
    Unknown = unumCount++
    Horizontal = unumCount++
    Vertical = unumCount++
```

**Comment by JoshuaKGoldberg** [comment]
Part of #49

**Comment by JoshuaKGoldberg** [comment]
Fun update here: As of #634, enum members are no longer guaranteed to have the value provided by GLS. It's now just a visual suggestion for what the value should be. We're lucky that, with the exception of Java, languages are able to use them. Java can't have plain integer values for their enum members, so it will no longer print out the values.

I'm going to close this issue. In theory GLS could provide some kind of default value in the enums, but that seems non-standard for languages.

/cc @faulda 🙂
