### ISSUE TITLE
Add a framework for compiling GLS-generated end-to-end test code

### ISSUE THREAD

**Issue by faulda** [general-language-syntax/GLS#55]
To validate that GLS is generating valid code, 1 or more tests should be added that do the following:
1. Compile GLS -> languages
2. Compile each language, fail test if any errors occur.

**Comment by JoshuaKGoldberg** [comment]
Ideally, each integration and end-to-end test would be compiled in each allowed output language.

**Comment by faulda** [comment]
Well some of them wouldn't be expected to. Like integration tests for commands don't include file start and main start and all that. In some languages (Java for example) without a class and a main, nothing will compile without errors. So unless we're going to add file and main start/end commands to every integration test, I think having 1 set of tests that covers the language surface area but don't include every integration test would be reasonable

**Comment by JoshuaKGoldberg** [comment]
Oh, duh. Agreed.

**Comment by JoshuaKGoldberg** [comment]
Making this a parent task as a prerequisite for language-specific ones. They'll each need their own runners.
* All but JavaScript and TypeScript have runtimes foreign to npm/Node.
* C#, Java, and TypeScript need to be compiled before running.

As a prerequisite, end-to-end tests should also have `print`s added so the runners can verify correct outputs. I would assume that means the end-to-end test source files should be renamed to `source.gls`/`source.ts`/etc., with an `output.txt`.

**Comment by JoshuaKGoldberg** [comment]
Just following up - this was done, except for #354's Java. Will track that separately.
