### ISSUE TITLE
Code coverage goes over 0 lines

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [general-language-syntax/GLS#79]
I knew 100% was too good to be true!

**Comment by JoshuaKGoldberg** [comment]
Pending investigation by @StevePeak & co.

https://gitter.im/codecov/support
> Steve Peak:
> There is a problem mapping the coverage back to your .ts files. All the reports include .js compiled versions of your coverage.

**Comment by stevepeak** [comment]
Checkout our new example repository: https://github.com/eddiemoore/example-typescript

**Comment by JoshuaKGoldberg** [comment]
Awesome, thanks @stevepeak! :)

**Comment by JoshuaKGoldberg** [comment]
Will restart in separate issue.
